# numpy basic to adv

In [1]:
import numpy as np

In [2]:
np.array([x*x for x in range(20)])

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [4]:
np.array([[1,2,3],[5,9,7]])

array([[1, 2, 3],
       [5, 9, 7]])

# Createing arrays in numpy

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
np.full((2,2), 5)

array([[5, 5],
       [5, 5]])

In [10]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

# most importeent numpy array is this np.arrange yoou can craete every order array using this np function

In [13]:
np.arange(1,5)

array([1, 2, 3, 4])

In [14]:
np.arange(9,100 , 5)

array([ 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89,
       94, 99])

In [15]:
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

# check the propertise of numpy arrays

In [24]:
arr = np.array([[1,2,3],[5,9,7]])
arr

array([[1, 2, 3],
       [5, 9, 7]])

In [18]:
arr.shape

(2, 3)

In [19]:
arr.size

6

In [20]:
arr.ndim

2

In [21]:
arr.dtype

dtype('int64')

# change the data type of numpy arrays

In [26]:
arr = np.array([[1,2,3],[5,9,7]] , dtype= np.float64)

In [27]:
arr

array([[1., 2., 3.],
       [5., 9., 7.]])

In [28]:
arr.dtype

dtype('float64')

In [30]:
arr = arr.astype(np.int32)

In [31]:
arr.dtype

dtype('int32')

# Reshapeing and flashing of numpy arrays

In [32]:
ar = np.array([[1,2,3],[5,9,7]])

In [33]:
ar.shape

(2, 3)

In [34]:
ar.reshape((3,2))

array([[1, 2],
       [3, 5],
       [9, 7]])

In [36]:
ar.flatten()

array([1, 2, 3, 5, 9, 7])

# Indexing and sliceing

In [38]:
numbers = np.array([1,2,3,4,5,6,7,8,9])

In [39]:
numbers[1]

np.int64(2)

In [40]:
numbers[1:5]

array([2, 3, 4, 5])

In [42]:
numbers[::4]

array([1, 5, 9])

In [43]:
numbers[0] =20

In [44]:
numbers

array([20,  2,  3,  4,  5,  6,  7,  8,  9])

In [51]:
marks = np.array([1,2,3,5,9,7])

In [54]:
x = marks[2:5].copy()

In [55]:
x

array([3, 5, 9])

In [56]:
marks_student = np.arange(1,100)

In [59]:
marks_student

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [60]:
index =[ 1,5,58,44,21]

In [63]:
marks_student[index]

array([ 2,  6, 59, 45, 22])

In [64]:
marks_student[marks_student>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [67]:
z = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
              [7, 8]]])


In [68]:
z.shape

(2, 2, 2)

In [69]:
z[0]

array([[1, 2],
       [3, 4]])

In [70]:
z[1]

array([[5, 6],
       [7, 8]])

In [72]:
z[1,1]

array([7, 8])

# vectorized opertaion in numpy arrays

In [74]:
xyz = np.array([1,2,3,4,5,6,7,8,9])
result = xyz*10
print(result)

[10 20 30 40 50 60 70 80 90]


In [75]:
xyz = np.array([1,2,3,4,5,6,7,8,9])
result = xyz +10
print(result)

[11 12 13 14 15 16 17 18 19]


In [77]:
arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[5,9,7]])
result_arr = arr_1d + arr_2d
print(result_arr)

[[ 2  4  6]
 [ 6 11 10]]


In [80]:
arr =np.array([[1,2,3]
               ,[5,9,7]
               ,[9,2,5]
               ,[8,5,7]])
arr.shape

(4, 3)

In [81]:
add = arr.sum(axis=1)
print(add)

[ 6 21 16 20]
