In [5]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [7]:
a = np.array([1,2,3,4,5,6,6,6])
c = a[1:4]
print(c)

[2 3 4]


In [8]:
a

array([1, 2, 3, 4, 5, 6, 6, 6])

In [9]:
c

array([2, 3, 4])

In [10]:
a[2:5]

array([3, 4, 5])

In [11]:
a

array([1, 2, 3, 4, 5, 6, 6, 6])

In [13]:
c = a[1:4].copy()

In [14]:
print(c)

[2 3 4]


In [15]:
c[2] = 5

In [16]:
print(c)

[2 3 5]


In [19]:
d = [1,2,3]

In [25]:
print(a[d])

[2 3 4]


In [27]:
a[a>5]

array([6, 6, 6])