In [1]:
import numpy as np

arr = np.array([5, 12, 7, 19, 3, 45, 8, 21, 33, 14, 56, 9, 2, 88, 17, 42, 67, 29, 90, 11, 25, 73])
print(arr)



[ 5 12  7 19  3 45  8 21 33 14 56  9  2 88 17 42 67 29 90 11 25 73]


In [12]:
arr[0]

np.int64(5)

In [13]:
print(arr[1:5])

[12  7 19  3]


In [14]:
print(arr[1:5])

[12  7 19  3]


In [17]:
arr[:3]

array([ 5, 12,  7])

In [18]:
arr[5:]

array([45,  8, 21, 33, 14, 56,  9,  2, 88, 17, 42, 67, 29, 90, 11, 25, 73])

In [19]:
arr[::3]

array([ 5, 19,  8, 14,  2, 42, 90, 73])

In [20]:
arr

array([ 5, 12,  7, 19,  3, 45,  8, 21, 33, 14, 56,  9,  2, 88, 17, 42, 67,
       29, 90, 11, 25, 73])

In [22]:
b = arr[3:9]

In [23]:
b[2] = 2222222222

In [24]:
b

array([        19,          3, 2222222222,          8,         21,
               33])

In [25]:
arr

array([         5,         12,          7,         19,          3,
       2222222222,          8,         21,         33,         14,
               56,          9,          2,         88,         17,
               42,         67,         29,         90,         11,
               25,         73])