In [6]:
#useing python list
import numpy as np
import time
size = 10000

l1 =list(range(size))
l2 =list(range(size))

start = time.time()
add =[x+y for x,y in zip(l1,l2)]
end =time.time()
print(end - start)


0.0007779598236083984


In [11]:
# useing numpy arrays

In [5]:
import numpy as np
import time
size = 10000

l1 =np.array(range(size))
l2 =np.array(range(size))

start = time.time()
add = l1 
end =time.time()
print(add[0:10])
print(end - start)

[0 1 2 3 4 5 6 7 8 9]
0.0008296966552734375


In [7]:
#python zip functons 

In [8]:
l1=[1,2,34,5]
l2 = [2,3,4,56,7]
list(zip(l1,l2))

[(1, 2), (2, 3), (34, 4), (5, 56)]

In [9]:
# numpy array

In [13]:
np.array([1,2,3,4,5,3,7,3,8])

array([1, 2, 3, 4, 5, 3, 7, 3, 8])

In [22]:
arr = np.array([[1,2,3],[3,4,5]])

In [23]:
type(arr)

numpy.ndarray

In [24]:
arr.shape

(2, 3)

In [26]:
import sys
list_data = list(range(100000))
numpy_data = np.array(range(100000))
numpydata =np.array(list_data)
print("python list syze",sys.getsizeof(list_data)*len(list_data),"bytes")
print("numpy array size" ,numpy_data.nbytes,"bytes")

python list syze 80005600000 bytes
numpy array size 800000 bytes


In [29]:
# numpy vectorization - no more loops!!

In [35]:
numpy_squre = arr**2
print(numpy_squre)

[[ 1  4  9]
 [ 9 16 25]]
