In [2]:
import numpy as np
import time

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,12])
print(arr)


[ 1  2  3  4  5  6  7  8 12]


In [6]:
arr2 = np.array([[1,2,3,4,56,6],[2,4,5,6,78,77]])
print(arr2)

[[ 1  2  3  4 56  6]
 [ 2  4  5  6 78 77]]


In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((7,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.arange(1,99,12)

array([ 1, 13, 25, 37, 49, 61, 73, 85, 97])

In [20]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [25]:
arr = np.full((7,4),9)

print(arr)


[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [26]:
arr.shape

(7, 4)

In [27]:
arr.size

28

In [31]:
arr.ndim

2

In [33]:
arr.dtype

dtype('int64')