In [2]:
import numpy as np
import time

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,12])
print(arr)


[ 1  2  3  4  5  6  7  8 12]


In [6]:
arr2 = np.array([[1,2,3,4,56,6],[2,4,5,6,78,77]])
print(arr2)

[[ 1  2  3  4 56  6]
 [ 2  4  5  6 78 77]]


In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])